### ISSUE TITLE
Publication of pre-trained model

### ISSUE THREAD

**Issue by chrismolli** [Clay-foundation/earth-text#27]
Hey guys, great work on the OSM embedding. I was wondering if the pretrained model that you used for the query examples in the notebooks is available somewhere.

If not I'd see this as my feature request ;)

**Comment by brunosan** [comment]
Hi @chrismolli.
Yes, it's published on Hugging Face. We should update the Readme.

https://huggingface.co/made-with-clay/Clay/tree/main

**Comment by chrismolli** [comment]
@brunosan thanks for the update, that's great to hear.
