### ISSUE TITLE
Progress updates

### ISSUE THREAD

**Issue by lauracchen** [Clay-foundation/earth-text#5]
Hello! So excited to see this repo and progress!

I'm not sure how this is organized internally, but for text-to-earth work, can we either add the tasks to the bi-weekly sprint in clay-foundation/office @yellowcap, or post sprint updates here? If it's organized on a bit of a different timeline or differently, that's totally fine, but I'm just hoping we can have some regular cadence of upcoming tasks/updates. Thank you!

cc @brunosan

**Comment by yellowcap** [comment]
I'll coordinate with Raul and Freddie today and weave their plan into the new sprint ticket today.

**Comment by yellowcap** [comment]
Created goals for this sprint and added to sprint ticket.

**Comment by lauracchen** [comment]
Thank you!! @yellowcap
