### ISSUE TITLE
Create v0.2 embeddgins for the California tiles

### ISSUE THREAD

**Issue by yellowcap** [Clay-foundation/earth-text#7]
Once we have the new model we can run embeddings for all of the ~100k tiles over California.

Depends on https://github.com/Clay-foundation/model/issues/190

**Comment by lauracchen** [comment]
@yellowcap will this be run/saving at the patch level? If so, may be an easy, ready-made set that our app team can use, so just want to flag to them.

**Comment by yellowcap** [comment]
The earth-text team needs the tile level embeddings, but we can create the patch level too, that is a good idea.

**Comment by lauracchen** [comment]
That would be great, thank you!

**Comment by brunosan** [comment]
Tagging here that this was done, as shared on chat:
We created the embeddings for the california chips using model v0.2. Under `s3://clay-text/california-worldcover-chips/` you have
* `embeddings_v0.2` : the embeddings per chip, of length 768 on each chip
* `patch_embeddings_v0.2` : the embeddings per patch, of shape 16x16x768 on each chip
* `osm` : the osm geometries of each chip (all of them, unfiltered)
* `esaworldcover-2020` : the corresponding chips with esa world cover classes, of shape 256x256 on each chip

Note also that I use sometimes [this function](https://github.com/Clay-foundation/earth-text/blob/0d4d7755f29b6501e0bb3a02187b9f1706356261/src/earthtext/osm/osm.py#L35) to generate unique identifiers for each chip. It creates a hash of the string representation of the geometry, so I can get unique identifiers of any shape.

the file `california-worldcover-chips-osm-multilabels.parquet` contains the metadata with the geometry, identifiers, osm tags and multilabel one hot encodings of each chip

**Comment by yellowcap** [comment]
Done
